apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ips.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: ips
    singular: ip
    kind: IP
    shortNames:
      - ip
  additionalPrinterColumns:
    - name: IP
      type: string
      JSONPath: .spec.ipAddress
    - name: Mac
      type: string
      JSONPath: .spec.macAddress
    - name: Node
      type: string
      JSONPath: .spec.nodeName
    - name: Subnet
      type: string
      JSONPath: .spec.subnet
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            podName:
              type: string
            namespace:
              type: string
            subnet:
              type: string
            attachSubnets:
              type: array
              items:
                type: string
            nodeName:
              type: string
            ipAddress:
              type: string
            attachIps:
              type: array
              items:
                type: string
            macAddress:
              type: string
            attachMacs:
              type: array
              items:
                type: string
            containerID:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subnets.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: subnets
    singular: subnet
    kind: Subnet
    shortNames:
      - subnet
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Provider
      type: string
      JSONPath: .spec.provider
    - name: Vpc
      type: string
      JSONPath: .spec.vpc
    - name: Protocol
      type: string
      JSONPath: .spec.protocol
    - name: CIDR
      type: string
      JSONPath: .spec.cidrBlock
    - name: Private
      type: boolean
      JSONPath: .spec.private
    - name: NAT
      type: boolean
      JSONPath: .spec.natOutgoing
    - name: ExternalEgressGateway
      type: string
      JSONPath: .spec.externalEgressGateway
    - name: PolicyRoutingPriority
      type: integer
      JSONPath: .spec.policyRoutingPriority
    - name: PolicyRoutingTableID
      type: integer
      JSONPath: .spec.policyRoutingTableID
    - name: Default
      type: boolean
      JSONPath: .spec.default
    - name: GatewayType
      type: string
      JSONPath: .spec.gatewayType
    - name: Used
      type: number
      JSONPath: .status.usingIPs
    - name: Available
      type: number
      JSONPath: .status.availableIPs
  validation:
    openAPIV3Schema:
      properties:
        status:
          type: object
          properties:
            availableIPs:
              type: number
            usingIPs:
              type: number
            activateGateway:
              type: string
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
                  lastUpdateTime:
                    type: string
                  lastTransitionTime:
                    type: string
        spec:
          type: object
          properties:
            vpc:
              type: string
            default:
              type: boolean
            protocol:
              type: string
            cidrBlock:
              type: string
            namespaces:
              type: array
              items:
                type: string
            gateway:
              type: string
            provider:
              type: string
            excludeIps:
              type: array
              items:
                type: string
            gatewayType:
              type: string
            allowSubnets:
              type: array
              items:
                type: string
            gatewayNode:
              type: string
            natOutgoing:
              type: boolean
            externalEgressGateway:
              type: string
            policyRoutingPriority:
              type: integer
              minimum: 1
              maximum: 32765
            policyRoutingTableID:
              type: integer
              minimum: 1
              maximum: 2147483647
              not:
                enum:
                  - 252 # compat
                  - 253 # default
                  - 254 # main
                  - 255 # local
            private:
              type: boolean
            vlan:
              type: string
            underlayGateway:
              type: boolean
            disableInterConnection:
              type: boolean
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vlans.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: vlans
    singular: vlan
    kind: Vlan
    shortNames:
      - vlan
  additionalPrinterColumns:
    - name: ID
      type: string
      JSONPath: .spec.id
    - name: Provider
      type: string
      JSONPath: .spec.provider
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              maximum: 4095
            provider:
              type: string
            vlanId:
              type: integer
              description: Deprecated in favor of id
            providerInterfaceName:
              type: string
              description: Deprecated in favor of provider
          required:
            - provider
        status:
          type: object
          properties:
            subnets:
              type: array
              items:
                type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: provider-networks.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: provider-networks
    singular: provider-network
    kind: ProviderNetwork
    listKind: ProviderNetworkList
  additionalPrinterColumns:
    - name: DefaultInterface
      type: string
      JSONPath: .spec.defaultInterface
    - name: Ready
      type: boolean
      JSONPath: .status.ready
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            defaultInterface:
              type: string
            customInterfaces:
              type: array
              items:
                type: object
                properties:
                  interface:
                    type: string
                  nodes:
                    type: array
                    items:
                      type: string
            excludeNodes:
              type: array
              items:
                type: string
          required:
            - defaultInterface
        status:
          type: object
          properties:
            ready:
              type: boolean
            readyNodes:
              type: array
              items:
                type: string
            vlans:
              type: array
              items:
                type: string
            conditions:
              type: array
              items:
                type: object
                properties:
                  node:
                    type: string
                  type:
                    type: string
                  status:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
                  lastUpdateTime:
                    type: string
                  lastTransitionTime:
                    type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vpcs.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: vpcs
    singular: vpc
    kind: Vpc
    listKind: VpcList
    shortNames:
    - vpc
  subresources:
    status: {}
  additionalPrinterColumns:
    - JSONPath: .status.standby
      name: Standby
      type: boolean
    - JSONPath: .status.subnets
      name: Subnets
      type: string
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            namespaces:
              items:
                type: string
              type: array
            staticRoutes:
              items:
                properties:
                  policy:
                    type: string
                  cidr:
                    type: string
                  nextHopIP:
                    type: string
                type: object
              type: array
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  lastUpdateTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
            default:
              type: boolean
            defaultLogicalSwitch:
              type: string
            router:
              type: string
            standby:
              type: boolean
            subnets:
              items:
                type: string
              type: array
            tcpLoadBalancer:
              type: string
            tcpSessionLoadBalancer:
              type: string
            udpLoadBalancer:
              type: string
            udpSessionLoadBalancer:
              type: string
          type: object
      type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vpc-nat-gateways.kubeovn.io
spec:
  group: kubeovn.io
  names:
    plural: vpc-nat-gateways
    singular: vpc-nat-gateway
    shortNames:
    - vpc-nat-gw
    kind: VpcNatGateway
    listKind: VpcNatGatewayList
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              dnatRules:
                type: array
                items:
                  type: object
                  properties:
                    eip:
                      type: string
                    externalPort:
                      type: string
                    internalIp:
                      type: string
                    internalPort:
                      type: string
                    protocol:
                      type: string
              eips:
                type: array
                items:
                  type: object
                  properties:
                    eipCIDR:
                      type: string
                    gateway:
                      type: string
              floatingIpRules:
                type: array
                items:
                  type: object
                  properties:
                    eip:
                      type: string
                    internalIp:
                      type: string
              lanIp:
                type: string
              snatRules:
                type: array
                items:
                  type: object
                  properties:
                    eip:
                      type: string
                    internalCIDR:
                      type: string
              subnet:
                type: string
              vpc:
                type: string
    subresources:
      status: {}
  conversion:
    strategy: None
